sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
      -
        handle: icon
        field:
          mode: list
          container: assets
          folder: /
          restrict: false
          allow_uploads: true
          show_filename: true
          max_files: 1
          display: Icon
          type: assets
          icon: assets
          listable: hidden
          instructions_position: above
          visibility: visible
      -
        handle: banner
        field:
          mode: list
          container: assets
          folder: /
          restrict: false
          allow_uploads: true
          show_filename: true
          max_files: 1
          display: Banner
          type: assets
          icon: assets
          listable: hidden
          instructions_position: above
          visibility: visible
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          localizable: true
title: site
