title: 'Global Settings'
sections:
  main:
    display: Main
    fields:
      -
        handle: site_name
        field:
          character_limit: 0
          type: text
          display: 'Site Name'
      -
        handle: favicon
        field:
          mode: list
          container: assets
          folder: /
          restrict: false
          allow_uploads: true
          show_filename: true
          max_files: 1
          display: Favicon
          type: assets
          icon: assets
          listable: hidden
          instructions_position: above
  meta:
    display: meta
    fields:
      -
        handle: nav_image
        field:
          mode: list
          container: assets
          folder: /
          restrict: false
          allow_uploads: true
          show_filename: true
          max_files: 1
          display: 'Nav Image'
          type: assets
          icon: assets
          listable: hidden
          instructions_position: above
          visibility: visible
