title: 'Global Settings'
sections:
  main:
    display: Main
    fields:
      -
        handle: site_name
        field:
          character_limit: 0
          type: text
          display: 'Site Name'
      -
        handle: favicon
        field:
          mode: list
          container: assets
          folder: /
          restrict: false
          allow_uploads: true
          show_filename: true
          max_files: 1
          display: Favicon
          type: assets
          icon: assets
          listable: hidden
          instructions_position: above
  meta:
    display: meta
    fields:
      -
        handle: nav_image
        field:
          mode: list
          container: assets
          folder: /
          restrict: false
          allow_uploads: true
          show_filename: true
          max_files: 1
          display: 'Nav Image'
          type: assets
          icon: assets
          listable: hidden
          instructions_position: above
          visibility: visible
      -
        handle: info_links
        field:
          fields:
            -
              handle: assets_field
              field:
                mode: list
                container: assets
                folder: /
                restrict: false
                allow_uploads: true
                show_filename: true
                max_files: 1
                display: 'Assets Field'
                type: assets
                icon: assets
                width: 25
                listable: hidden
                instructions_position: above
                visibility: visible
            -
              handle: title
              field:
                input_type: text
                antlers: false
                display: Title
                type: text
                icon: text
                listable: hidden
                instructions_position: above
                visibility: visible
            -
              handle: url
              field:
                input_type: text
                antlers: false
                display: Url
                type: text
                icon: text
                listable: hidden
                instructions_position: above
                visibility: visible
          mode: table
          reorderable: true
          display: 'Info Links'
          type: grid
          icon: grid
          listable: hidden
          instructions_position: above
          visibility: visible
